### ISSUE TITLE
IOS - Overlapping Text input

### ISSUE THREAD

**Issue by ImAbhishekTomar** [karanpratapsingh/Proximity#20]
Overlapping Text input... device iPhone 10 iOS 13.3

![A4D7DE6F-932F-4921-B847-149F0543EE9B](https://user-images.githubusercontent.com/6933841/70917209-e1c13280-2057-11ea-984f-0a0487e26424.jpeg)

**Comment by karanpratapsingh** [comment]
Thank you for reporting, will fix in next release 😄, this doesn't happen in pre-X ios devices

**Comment by karanpratapsingh** [comment]
Fixed, it's available in OTA 1.7.5 or new update coming around new year 😊
