### ISSUE TITLE
Unable to resolve module `./app/config` from `App.tsx`:

### ISSUE THREAD

**Issue by bunyaminmrcn** [karanpratapsingh/Proximity#23]
Hi . While running the app Show the error message this. 

- Unable to resolve module `./app/config` from `App.tsx`:

Can you push sample config file

**Comment by hawke9000** [comment]
Were you able to figure this out? I kind of figured I was supposed to put a key “$APP_ID=****Google_Client-
_ID***”

But I am probably wrong

**Comment by karanpratapsingh** [comment]
Hey guys I am setting up a dev config for everyone, sorry for the late reply. It's been a busy month

**Comment by hawke9000** [comment]
thank you 💯 I have been trying really hard to create this project and have had no luck at all. Only just now started figuring out the last bits of the Apollo / Heroku integration and CodePush stuff.

**Comment by karanpratapsingh** [comment]
@hawke9000 @bunyaminmrcn please do a fresh clone of the repo now and run, it should work, I've added added secret files (without keys ofc) and in dev env mode
