### ISSUE TITLE
 Unable to resolve module `react-native-screens`

### ISSUE THREAD

**Issue by eramudeep** [karanpratapsingh/Proximity#28]
cloned the app,
* npm install
* react-native run-android

*Build get successful but the error comes up* 
error: bundling failed: Error: Unable to resolve module `react-native-screens` from `node_modules\react-navigation-stack\lib\module\views\StackView\StackViewCard.js`: react-native-screens could not be found within the project.

**Comment by karanpratapsingh** [comment]
which branch did you run? this was fixed on develop branch. make sure do do `yarn` as I updated dependencies

**Comment by eramudeep** [comment]
i used master  branch.
let me try with development.
Thank you for your reply.

**Comment by karanpratapsingh** [comment]
Hey can you try using yarn rather than npm? It seems to have fixed similar issue

**Comment by eramudeep** [comment]
having same problem. 

taken a new clone.
checkout from the development branch 
yarn install not worked:
error: **Incorrect integrity when fetching from the cache**
npm install
react-native run-android

**Comment by eramudeep** [comment]
Yo Man Yarn worked for me .
Thank you !!!!
