### ISSUE TITLE
Unable to run app (npm run ios)

### ISSUE THREAD

**Issue by samazadi** [karanpratapsingh/Proximity#29]
**Steps to reproduce**
`git clone https://github.com/karanpratapsingh/Proximity.git`
`cd Proximity`
`npm i`
`cd ios && pod install`
`cd ..`
`npm run ios`

Metro builder starts up and throws the following error:
`Error: EMFILE: too many open files, watch
    at FSEvent.FSWatcher._handle.onchange (internal/fs/watchers.js:123:28)
Emitted 'error' event at:
    at NodeWatcher.checkedEmitError (/Users/samghodrati-azadi/Documents/Repo/Proximity/node_modules/sane/src/node_watcher.js:143:12)
    at FSWatcher.emit (events.js:198:13)
    at FSEvent.FSWatcher._handle.onchange (internal/fs/watchers.js:129:12)
Process terminated. Press <enter> to close the window`

**Expected behavior**
App should start up

<img width="976" alt="Screen Shot 2020-03-13 at 11 38 25 PM" src="https://user-images.githubusercontent.com/13510296/76676825-6ef72300-6584-11ea-8509-ecbe7b856334.png">

**Comment by karanpratapsingh** [comment]
I think this is a watchman issue, try the following steps:

`$ brew update`
`$ brew install watchman`

If you don't have brew, do this first:

```
/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
```

**Comment by karanpratapsingh** [comment]
Thanks, I left a comment

**Comment by samazadi** [comment]
Thanks for your reply.
That fixed that issue, but now I'm running into the same problem as issue #28 . I am using the development branch.

**Comment by karanpratapsingh** [comment]
I'm not sure why this is happening, I did a fresh clone and just did 
``` 
yarn && yarn cocoapods && yarn ios
```
and it worked perfectly, same goes for android

**Comment by samazadi** [comment]
Using yarn it worked! Thank you :)
