### ISSUE TITLE
private keys

### ISSUE THREAD

**Issue by bradenboothby** [karanpratapsingh/Proximity#31]
where do i input all of my private keys? database, firebase, etc

**Comment by karanpratapsingh** [comment]
Hey Braden, all the keys (development) are in place, for running the project on your machine you just need to 

1. clone the repo
2. yarn (install node_module)
3. yarn cocoapods (skip for android)
4. yarn ios (start the simulator)

if you want to input your own keys then the files are: 

1. ios/Google-Info.plist and android/app/google-services.json (firebase)
2. ios/Config.xcconfig
3. app/config/index.ts
