### ISSUE TITLE
Can you please opensource graphql backend?

### ISSUE THREAD

**Issue by ravisojitra** [karanpratapsingh/Proximity#34]
This project is so good and right now i am learning graphql. It would be great help if you can also opensource graphql backend.

**Comment by EduardoRicardez** [comment]
x2 plsss!

**Comment by EduardoRicardez** [comment]
i want to see the graphQL backend

**Comment by lil-h** [comment]
https://gist.github.com/lil-h/84c7a2345147d86dc13512ca0f148d4b

**Comment by ravisojitra** [comment]
@lil-h is this same from proximity? or from another app?

**Comment by lil-h** [comment]
I thought it was the one I combined. I guess not. Will remove...

**Comment by lil-h** [comment]
I have been working on a large add on to this project I hope you will like by the way! I want to see this succeed

**Comment by ravisojitra** [comment]
sure... where can i track that add?

**Comment by lil-h** [comment]
I can add it as a new branch If you would like. I have had a tough time getting Codepush to work since updating the package.json dependencies though.

**Comment by ravisojitra** [comment]
@lil-h ok thanks, that would be great.

**Comment by karanpratapsingh** [comment]
@ravisojitra @lil-h @EduardoRicardez For GraphQL schema please take a look at `app/graphql/schema/schema.graphql`, now you should be able to build out your own backend, with Prisma 2 being released it would be way simpler than prisma 1. thanks

**Comment by roshangm1** [comment]
Don't have backend expertise. Can you provide some guide on how should I proceed on creating own backend with the schema file ? @karanpratapsingh
